In [100]:
import db
import LSTM_utils
import pprint
from pprint import pprint
import numpy as np
from numpy import array
from numpy import hstack
import pandas as pd
import datetime


In [85]:
sym_array = ['/ES', '/CL', '/GC']
main_df = pd.DataFrame()
""" request data from DB """
for sym in sym_array:
  data = db.get_symbol(sym, 10)
#   pprint(data)
  sym = sym[1:]
  df = pd.DataFrame.from_dict(data).drop(['start_timestamp'], axis=1).rename(columns={"open":f"{sym}_open", "high":f"{sym}_high", "low":f"{sym}_low", "close":f"{sym}_close", "volume":f"{sym}_volume"})

  if(len(main_df) == 0):
    main_df = df
  else:
    main_df = main_df.join(df)

In [69]:
n_steps = 3

es_X, es_y, = LSTM_utils.split_sequence(es_data, n_steps)
cl_X, cl_y, = LSTM_utils.split_sequence(cl_data, n_steps)
gc_X, gc_y, = LSTM_utils.split_sequence(gc_data, n_steps)
print(es_X)
print(es_y)
print(es_X.shape)#(80, 20, 1)

es_y = es_y.reshape(1, len(es_y), 1)
print(es_y.shape)#(80, 1)
print(es_y)

[[[2963.75]
  [2963.5 ]
  [2963.75]]

 [[2963.5 ]
  [2963.75]
  [2964.  ]]

 [[2963.75]
  [2964.  ]
  [2977.25]]]
[[2964.  ]
 [2977.25]
 [2977.25]]
(3, 3, 1)
(1, 3, 1)
[[[2964.  ]
  [2977.25]
  [2977.25]]]


In [91]:

# multivariate data preparation
from numpy import array
from numpy import hstack
 
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)
# summarize the data
pprint(X)
pprint(y)


(7, 3, 2) (7,)
array([[[10, 15],
        [20, 25],
        [30, 35]],

       [[20, 25],
        [30, 35],
        [40, 45]],

       [[30, 35],
        [40, 45],
        [50, 55]],

       [[40, 45],
        [50, 55],
        [60, 65]],

       [[50, 55],
        [60, 65],
        [70, 75]],

       [[60, 65],
        [70, 75],
        [80, 85]],

       [[70, 75],
        [80, 85],
        [90, 95]]])
array([ 65,  85, 105, 125, 145, 165, 185])


In [116]:
d = [[i for i in range(100)]]
# d = [i for i in range(100)]

In [117]:
print(d)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]


In [43]:
print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [109]:
a = ([[1, 2, 3]])
b = ([[4, 5, 6]])

In [112]:
c = np.concatenate((a, b))

In [113]:
pprint(c)

array([[1, 2, 3],
       [4, 5, 6]])
